command /join:
	executable by: player
	trigger:
		if {Join::%player%} is set:
			message "§cあなたは既にゲームに参加しています" to player
		else:
			log "これからつくる"

command /joinset <number> <text>:
	permission: sk.admin
	trigger:
		set {%arg 2%-Join} to arg 1
		message "§b%arg 2%§7の現在の参加人数を§a%{%arg 2%-Join}%§7に設定しました"

command /leave:
	executable by: player
	trigger:
		if {Join::%player%} is "Kit":
			log "これからつくる"
		else:
			message "§cあなたはゲームに参加していません。" to player