aliases:
#	physicblock1 = minecraft:white_concrete_powder, minecraft:orange_concrete_powder, minecraft:magenta_concrete_powder, minecraft:light_blue_concrete_powder, minecraft:yellow_concrete_powder, minecraft:lime_concrete_powder, minecraft:pink_concrete_powder, minecraft:gray_concrete_powder, minecraft:light_gray_concrete_powder, minecraft:cyan_concrete_powder, minecraft:purple_concrete_powder, minecraft:blue_concrete_powder, minecraft:brown_concrete_powder, minecraft:green_concrete_powder, minecraft:red_concrete_powder, minecraft:black_concrete_powder, minecraft:oak_sapling, minecraft:birch_sapling, minecraft:spruce_sapling, minecraft:jungle_sapling, minecraft:acacia_sapling, minecraft:dark_oak_sapling, minecraft_sand, minecraft_red_sand, minecraft:gravel, minecraft:grass, minecraft:fern, minecraft:dead_bush, minecraft:seagrass, minecraft:sea_pickle
#	physicblock2 = minecraft:dandelion, minecraft:poppy, minecraft:blue_orchid, minecraft:allium, minecraft:azure_bluet, minecraft:red_tulip, minecraft:orange_tulip, minecraft:white_tulip, minecraft:pink_tulip, minecraft:oxeye_daisy, minecraft:cornflower, minecraft:lily_of_the_valley, minecraft:wither_rose, minecraft:brown_mushroom, minecraft:red_mushroom, minecraft:torch, minecraft:wheat, minecraft:farmland, minecraft:chorus_plant, minecraft:chorus_flower, minecraft:acacia_sign, minecraft:oak_sign, minecraft:birch_sign, minecraft:spruce_sign, minecraft:jungle_sign, minecraft:dark_oak_sign, minecraft:ladder, minecraft:rail, minecraft:oak_wall_sign, minecraft:spruce_wall_sign, minecraft:birch_wall_sign, minecraft:jungle_wall_sign, minecraft:acacia_wall_sign, minecraft:dark_oak_wall_sign, minecraft:snow, minecraft:cactus, minecraft:sugar_cane, minecraft:cake, minecraft:pumpkin_stem, minecraft:melon_stem, minecraft:vine, minecraft:lily_pad, minecraft:nether_wart, minecraft:dragon_egg
#	physicblock3 = minecraft:cocoa, minecraft:flower_pot, minecraft:carrots, minecraft:potatoes, minecraft:anvil, minecraft:chipped_anvil, minecraft:damaged_anvil, minecraft:white_carpet, minecraft:orange_carpet, minecraft:magenta_carpet, minecraft:light_blue_carpet, minecraft:yellow_carpet, minecraft:lime_carpet, minecraft:pink_carpet, minecraft:gray_carpet, minecraft:light_gray_carpet, minecraft:cyan_carpet, minecraft:purple_carpet, minecraft:blue_carpet, minecraft:brown_carpet, minecraft:green_carpet, minecraft:red_carpet, minecraft:black_carpet, minecraft:grass_path, minecraft:sunflower, minecraft:lilac, minecraft:rose_bush, minecraft:peony, minecraft:tall_grass, minecraft:large_fern
#	physicblock4 = minecraft:white_banner, minecraft:orange_banner, minecraft:magenta_banner, minecraft:light_blue_banner, minecraft:yellow_banner, minecraft:lime_banner, minecraft:pink_banner, minecraft:gray_banner, minecraft:light_gray_banner, minecraft:cyan_banner, minecraft:purple_banner, minecraft:blue_banner, minecraft:brown_banner, minecraft:green_banner, minecraft:red_banner, minecraft:black_banner, minecraft:white_wall_banner, minecraft:orange_wall_banner, minecraft:magenta_wall_banner, minecraft:light_blue_wall_banner, minecraft:yellow_wall_banner, minecraft:lime_wall_banner, minecraft:pink_wall_banner, minecraft:gray_wall_banner, minecraft:light_gray_wall_banner, minecraft:cyan_wall_banner, minecraft:purple_wall_banner, minecraft:blue_wall_banner, minecraft:brown_wall_banner, minecraft:green_wall_banner, minecraft:red_wall_banner, minecraft:black_wall_banner
#	physicblock5 = minecraft:tube_coral, minecraft:brain_coral, minecraft:bubble_coral, minecraft:fire_coral, minecraft:horn_coral, minecraft:dead_tube_coral, minecraft:dead_brain_coral, minecraft:dead_bubble_coral, minecraft:dead_fire_coral, minecraft:dead_horn_coral, minecraft:tube_coral_fan, minecraft:brain_coral_fan, minecraft:bubble_coral_fan, minecraft:fire_coral_fan, minecraft:horn_coral_fan, minecraft:dead_tube_coral_fan, minecraft:dead_brain_coral_fan, minecraft:dead_bubble_coral_fan, minecraft:dead_fire_coral_fan, minecraft:dead_horn_coral_fan, minecraft:scaffolding, minecraft:turtle_egg, minecraft:kelp, minecraft:kelp_plant, minecraft:bamboo, minecraft:bamboo_sapling
	redsignal1 = minecraft:dispenser, minecraft:note_block, minecraft:sticky_piston, minecraft:piston, minecraft:lever, minecraft:stone_pressure_plate, minecraft:oak_pressure_plate, minecraft:spruce_pressure_plate, minecraft:birch_pressure_plate, minecraft:jungle_pressure_plate, minecraft:acacia_pressure_plate, minecraft:dark_oak_pressure_plate, minecraft:redstone_torch, minecraft:redstone_wall_torch, minecraft:stone_button, minecraft:oak_button, minecraft:spruce_button, minecraft:birch_button, minecraft:jungle_button, minecraft:acacia_button, minecraft:dark_oak_button, minecraft:oak_trapdoor, minecraft:spruce_trapdoor, minecraft:birch_trapdoor, minecraft:jungle_trapdoor, minecraft:acacia_trapdoor, minecraft:dark_oak_trapdoor, minecraft:oak_fence_gate, minecraft:spruce_fence_gate, minecraft:birch_fence_gate, minecraft:jungle_fence_gate, minecraft:acacia_fence_gate, minecraft:dark_oak_fence_gate
	redsignal2 = minecraft:oak_door, minecraft:spruce_door, minecraft:birch_door, minecraft:jungle_door, minecraft:acacia_door, minecraft:dark_oak_door, minecraft:redstone_lamp, minecraft:tripwire_hook, minecraft:tripwire, minecraft:trapped_chest, minecraft:light_weighted_pressure_plate, minecraft:heavy_weighted_pressure_plate, minecraft:daylight_detector, minecraft:hopper, minecraft:dropper, minecraft:iron_trapdoor, minecraft:observer, minecraft:iron_door, minecraft:repeater, minecraft:comparator, minecraft:redstone_wire, minecraft:lectern, minecraft:powered_rail, minecraft:detector_rail, minecraft:activator_rail, minecraft:redstone_block, minecraft:command_block, minecraft:chain_command_block, minecraft:repeating_command_block
#	likeair = 0, 6, 8, 9, 10, 11, 18, 20, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 46, 50, 51, 54, 55, 59, 60, 63, 64, 65, 66, 68, 69, 70, 71, 72, 75, 76, 77, 78, 79, 81, 83, 85, 90, 92, 93, 94, 95, 96, 101, 102, 104, 104, 106, 107, 111, 113, 115, 116, 117, 118, 119, 120, 122, 127, 130, 131, 132, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 154, 157, 160, 161, 165, 167, 169, 171, 175, 176, 177, 178, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197

command /physics <boolean>:
	permission: sk.admin
	trigger:
		set {BlockPhysics} to arg 1
		message "§bBlockPhysic §9を §a%arg 1% §9に設定しました"

on physics:
	if world of event-location is "Kit-StoneRiver":
		if type of event-block is water:
			stop
	if {BlockPhysics} is true:
		if event-block is not redsignal1 or redsignal2:
			cancel event
#	else if event-block is redsignal:
#		if block below event-block is likeair:
#			cancel event
#	loop {Physics::*}:
#		loop-value is true
#		set {_true} to true
#	{_true} is true
#	cancel event

on entity block change:
	if entity is a falling fire:
		if "%world of event-location%" contains "Kit-":
			if "%world of event-location%" is "Kit-Volcano":
				stop
			else:
				cancel event
		else:
			cancel event
	else:
		cancel event

on flow:
	if world of event-location is "Kit-StoneRiver", "Lobby_nether" or "Lobby":
		stop
	cancel event

on fade:
	cancel event

on form:
	cancel event

on grow:
	cancel event

on burn:
	cancel event

on leaves decay:
	cancel event