on join:
	set the player's game mode to survival
	message "§6ようこそ! §a%player% §6さん"
	set join message to "§a%player% §bさんが参加しました!"
	wait a second
	player is online
	if {UUID::%player's UUID%} is not player:
		loop all players:
			loop-player has permission "sk.admin"
			message "§c[§6!§c] §e過去のユーザ名§7: §a%{UUID::%player's UUID%}%" to loop-player
	set {UUID::%player's UUID%} to player

on quit:
	set quit message to "§a%player% §dさんが退出しました!"